In [8]:
import numpy as np

3 variables system of linear equations¶

In [134]:
n= 3 #設定矩陣大小
np.random.seed(0) #隨機變數 
A= np.random.randint(-9,9,size=(n,n)) #random.randint(最小值,最大值,矩陣尺寸(行,列))
np.random.seed(1) 
b= np.random.randint(-9,9,size=(n,1)) 
x= np.linalg.solve(A, b) 

print( 
f'''
n= {n},  
A= 
{A} 
b= 
{b} 
x= 
{x} 
''') 


n= 3,  
A= 
[[ 3  6 -9]
 [-6 -6 -2]
 [ 0 -5 -3]] 
b= 
[[-4]
 [ 2]
 [ 3]] 
x= 
[[ 0.29378531]
 [-0.66101695]
 [ 0.10169492]] 



驗證

In [135]:
print(A.dot(x))

[[-4.]
 [ 2.]
 [ 3.]]


5 variables system of linear equations¶

In [144]:
n= 5 
np.random.seed(0) 
A= np.random.randint(-9,9,size=(n,n)) 
np.random.seed(1) 
b= np.random.randint(-9,9,size=(n,1)) 
x= np.linalg.solve(A, b) 

print( 
f'''
n= {n},  
A= 
{A} 
b= 
{b} 
x= 
{x} 
''') 


n= 5,  
A= 
[[ 3  6 -9 -6 -6]
 [-2  0 -5 -3  3]
 [-8 -3 -2  5  8]
 [-4  4 -1  0  7]
 [-4  6  6 -9 -6]] 
b= 
[[-4]
 [ 2]
 [ 3]
 [-1]
 [ 0]] 
x= 
[[-0.23675578]
 [-0.74933027]
 [ 0.06470395]
 [-0.45738341]
 [ 0.15928599]] 



驗證

In [138]:
print(A.dot(x))

[[-4.00000000e+00]
 [ 2.00000000e+00]
 [ 3.00000000e+00]
 [-1.00000000e+00]
 [-3.55271368e-15]
 [ 2.00000000e+00]
 [-4.00000000e+00]
 [ 6.00000000e+00]
 [-9.00000000e+00]
 [ 7.00000000e+00]]


10 variables system of linear equations¶

In [137]:
n= 10 
np.random.seed(0) 
A= np.random.randint(-9,9,size=(n,n)) 
np.random.seed(1) 
b= np.random.randint(-9,9,size=(n,1)) 
x= np.linalg.solve(A, b) 

print( 
f'''
n= {n},  
A= 
{A} 
b= 
{b} 
x= 
{x} 
''') 


n= 10,  
A= 
[[ 3  6 -9 -6 -6 -2  0 -5 -3  3]
 [-8 -3 -2  5  8 -4  4 -1  0  7]
 [-4  6  6 -9 -6  8  5 -2 -9 -8]
 [ 0 -9  1 -6  2 -7 -9 -9 -5 -4]
 [-3 -1  8  6 -5  0  1 -8 -8 -2]
 [ 0 -6 -3  2  5 -9  5 -6  3  1]
 [ 2 -5 -3 -5  6 -6  3 -5 -1  5]
 [ 6 -6  6  4  7  8 -4  0 -6 -9]
 [-4 -9  8 -5 -7  7 -6 -7  1  4]
 [ 7 -2  0 -9  1  2 -7 -7 -6 -6]] 
b= 
[[-4]
 [ 2]
 [ 3]
 [-1]
 [ 0]
 [ 2]
 [-4]
 [ 6]
 [-9]
 [ 7]] 
x= 
[[-0.31672593]
 [ 2.02924179]
 [ 0.61111213]
 [ 0.1590312 ]
 [ 1.67875253]
 [ 0.33624215]
 [-0.57482548]
 [-1.66325201]
 [ 1.33296729]
 [-0.78114507]] 



驗證

In [139]:
print(A.dot(x))

[[-4.00000000e+00]
 [ 2.00000000e+00]
 [ 3.00000000e+00]
 [-1.00000000e+00]
 [-3.55271368e-15]
 [ 2.00000000e+00]
 [-4.00000000e+00]
 [ 6.00000000e+00]
 [-9.00000000e+00]
 [ 7.00000000e+00]]
