In [2]:
x= 1
y= 2
z= x+y

x,y,z

(1, 2, 3)

In [4]:

def f(x,y):
    z= x+y
    return z

f(2, 3)

5

In [5]:
def add(x,y):
    z= x+y
    return z
def sub(x,y):
    z= x-y
    return z
def mul(x,y):
    z= x*y
    return z
def div(x,y):
    z= x/y
    return z

a= add(1,2)
s= sub(1,2)
m= mul(1,2)
d= div(1,2)
a,s,m,d

(3, -1, 2, 0.5)

In [6]:
x= 1
y= 2
z= x*y

x,y,z

(1, 2, 2)

In [7]:
x= 1
y= 2
z= x/y

x,y,z

(1, 2, 0.5)

In [4]:
class Number:
    
    def __init__(self,x=0):
        self.x= x
        
    def add(self,y):
        z= self.x + y
        return z
    
    def sub(self,y):
        z= self.x - y
        return z
    
    def mul(self,y):
        z= self.x * y
        return z
    
    def div(self,y):
        z= self.x / y
        return z

n= Number(100)
a= n.add(1)
s= n.sub(2)
m= n.mul(4)
d= n.div(5)
n, n.x, a, s, m, d

(<__main__.Number at 0x2064e6f2c10>, 100, 101, 98, 400, 20.0)

In [9]:

# 運用繼承的觀念，繼續擴充 物件內涵
# dunder (double under，雙底線) __xxx__

class Number(Number):
        
    def __add__(self,y):
        z= self.add(y)
        return z
    def __sub__(self,y):
        z= self.sub(y)
        return z
    def __mul__(self,y):
        z= self.mul(y)
        return z
    def __truediv__(self,y): # 這個除法的名稱比較特殊
        z= self.div(y)
        return z


n= Number(100)
a= n.add(1)
s= n.sub(1)
m= n.mul(1)
d= n.div(1)
n, n.x, a, s, m, d

(<__main__.Number at 0x2064e789eb0>, 100, 101, 99, 100, 100.0)

In [10]:
# __xxx___  double under (dunder)
a= n.__add__(4)
s= n.__sub__(5)
m= n.__mul__(2)
d= n.__truediv__(2)
n, n.x, a, s, m, d


(<__main__.Number at 0x2064e789eb0>, 100, 104, 95, 200, 50.0)

In [11]:
a= n+2
s= n-2
m= n*2
d= n/2
n, n.x, a, s, m, d

(<__main__.Number at 0x2064e789eb0>, 100, 102, 98, 200, 50.0)

In [12]:
class Number(Number):
    
    # print our string object
    def __repr__(self):      # 更改 此 物件的 print() 結果。 以字串型態送出去。
        return f'{self.x}'
    pass
    
    
n= Number(100)
n


100

In [13]:
type(n)

__main__.Number

In [14]:
# 向量的加減乘除四則運算

In [15]:
x= [1,2,3]
y= [10,20,30]
x+y

[1, 2, 3, 10, 20, 30]

In [17]:
x-y, x*y, x/y

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [18]:

# Python List 的 運算 +, -, * , / 不是 我們在數學上向量、矩陣、、、等的定義方式。
# 自己定義一個向量物件，使其符合數學上的定義！

In [19]:
class Vector:
    def __init__(self, x):
        self.x= x
        
    def add(self,y):    
        z= [xi+yi for xi,yi in zip(self.x, y)]
        return z

v= Vector([1,2,3,4])
v.add([10,20,30,40])

[11, 22, 33, 44]

In [20]:
# 把它擴展成 +, - , *, / 都可以


In [21]:
class Vector:
    def __init__(self, x):
        self.x= x
        
    def add(self,y):    
        z= [xi+yi for xi,yi in zip(self.x, y)]
        return z
    def sub(self,y):    
        z= [xi-yi for xi,yi in zip(self.x, y)]
        return z
    def mul(self,y):    
        z= [xi*yi for xi,yi in zip(self.x, y)]
        return z
    def div(self,y):    
        z= [xi/yi for xi,yi in zip(self.x, y)]
        return z
    
    def __add__(self,y):    
        z= self.add(y)
        return z
    def __sub__(self,y):    
        z= self.sub(y)
        return z
    def __mul__(self,y):    
        z= self.mul(y)
        return z
    def __truediv__(self,y):    
        z= self.div(y)
        return z

v= Vector([1,2,3,4])
v, v.x

(<__main__.Vector at 0x2064e789280>, [1, 2, 3, 4])

In [22]:
a= v + [10,20,30,40]
s= v - [10,20,30,40]
m= v * [10,20,30,40]
d= v / [10,20,30,40]
v.x, a, s, m, d

([1, 2, 3, 4],
 [11, 22, 33, 44],
 [-9, -18, -27, -36],
 [10, 40, 90, 160],
 [0.1, 0.1, 0.1, 0.1])

In [23]:
import numpy as np


In [24]:
v= [1, 2, 3, 4]
v

[1, 2, 3, 4]

In [25]:
v= np.array(v)
v

array([1, 2, 3, 4])

In [26]:
v.shape

(4,)

In [27]:
A= [[1,2,3,4],
    [5,6,7,8]]
A

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [28]:
A= np.array(A)
A

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
A.shape

(2, 4)

In [30]:
T=[[1,2,3,4],
   [5,6,7,8],
   [9,10,11,12],
   [13,14,15,16]]
T

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

In [31]:
T= np.array(T)
T

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [32]:
T.shape

(4, 4)

In [33]:
T= T.reshape((2,2,4))
T

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [34]:
T.shape

(2, 2, 4)

In [35]:
T[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [36]:
T[1]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [37]:
v.ndim

1

In [38]:
A.ndim

2

In [39]:
T.ndim

3

In [40]:
T4d= T.reshape(2,2,2,2)
T4d

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [41]:
T4d.shape

(2, 2, 2, 2)

In [42]:
v, A, T, T4d

(array([1, 2, 3, 4]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],
 
        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]]]),
 array([[[[ 1,  2],
          [ 3,  4]],
 
         [[ 5,  6],
          [ 7,  8]]],
 
 
        [[[ 9, 10],
          [11, 12]],
 
         [[13, 14],
          [15, 16]]]]))

In [43]:
v

array([1, 2, 3, 4])

In [44]:
v14= v.reshape(1,4)
v14

array([[1, 2, 3, 4]])

In [45]:
v41= v.reshape(4,1)
v41

array([[1],
       [2],
       [3],
       [4]])

In [46]:
v.shape, v14.shape, v41.shape

((4,), (1, 4), (4, 1))