In [1]:
import os
import sys
import glob
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
%matplotlib inline
%precision 4
plt.style.use('ggplot')


LU Decomposition and Gaussian Elimination

In [10]:
import numpy as np
import scipy.linalg as la
np.set_printoptions(suppress=True)

A = np.array([[1,3,4],[2,1,3],[4,1,2]])

L = np.array([[1,0,0],[2,1,0],[3,15/8,1]])
U = np.array([[1,2,3],[0,-8,0],[0,0,-12]])
print(L.dot(U))
print(L)
print(U)

[[ 1.  2.  3.]
 [ 2. -4.  6.]
 [ 3. -9. -3.]]
[[1.    0.    0.   ]
 [2.    1.    0.   ]
 [3.    1.875 1.   ]]
[[  1   2   3]
 [  0  -8   0]
 [  0   0 -12]]


In [8]:

import numpy as np
import scipy.linalg as la
np.set_printoptions(suppress=True)

A = np.array([[1,2,3],[2,-4,6],[3,-9,-3]])

print(A)

P, L, U = la.lu(A)
print(np.dot(P.T, A))
print(np.dot(L, U))
print("P = \n",P)
print("L = \n",L)
print("U = \n",U)

[[ 1  2  3]
 [ 2 -4  6]
 [ 3 -9 -3]]
[[ 3. -9. -3.]
 [ 1.  2.  3.]
 [ 2. -4.  6.]]
[[ 3. -9. -3.]
 [ 1.  2.  3.]
 [ 2. -4.  6.]]
P = 
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L = 
 [[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [0.66666667 0.4        1.        ]]
U = 
 [[ 3.  -9.  -3. ]
 [ 0.   5.   4. ]
 [ 0.   0.   6.4]]


Eigendecomposition

In [5]:
A = np.array([[1,2,3],[2,-4,6],[3,-9,-3]])

u, V = la.eig(A)
print(np.dot(V,np.dot(np.diag(u), la.inv(V))))
print(u)

[[ 1.-0.j  2.-0.j  3.+0.j]
 [ 2.-0.j -4.+0.j  6.-0.j]
 [ 3.-0.j -9.+0.j -3.-0.j]]
[ 1.64015533+0.j         -3.82007767+6.62857814j -3.82007767-6.62857814j]


In [6]:
A = np.array([[0,1],[-1,0]])
print(A)

u, V = la.eig(A)
print(np.dot(V,np.dot(np.diag(u), la.inv(V))))
print(u)

[[ 0  1]
 [-1  0]]
[[ 0.+0.j  1.+0.j]
 [-1.+0.j  0.+0.j]]
[0.+1.j 0.-1.j]


In [7]:
A = np.array([[1,2,3],[2,-4,6],[3,-9,-3]])
u, V = la.eig(A)
print(u)
print (np.real_if_close(u))

[ 1.64015533+0.j         -3.82007767+6.62857814j -3.82007767-6.62857814j]
[ 1.64015533+0.j         -3.82007767+6.62857814j -3.82007767-6.62857814j]
